### ISSUE TITLE
Is there any way to apply a border radius to the logo?

### ISSUE THREAD

**Issue by ka1ku** [tokkozhin/react-native-qrcode-styled#13]
This package has proven super awesome. I am trying to make the logo image circular, and cannot seem to figure out a solution. I have been trying to use "ClipPath," but I can't quite seem to get it working. Are there any workarounds to display a circular photo other than just editing the photo itself?

Edit: Resolved

**Comment by ka1ku** [comment]
fixed

**Comment by fontanamichele** [comment]
How do you resolve it?

**Comment by Holybasil** [comment]
could you share your solution here?
