### ISSUE TITLE
How to set a fixed width and height for QR code

### ISSUE THREAD

**Issue by alecdewitz** [tokkozhin/react-native-qrcode-styled#4]
If I want to set a fixed width for a dynamic QR code, how would I do that?

If the data is smaller than my set width and height, it doesn't fill the whole container and scale up. On the flip side, if my data is larger, it goes outside the bounds of the container.

How would I achieve this?

![image](https://github.com/tokkozhin/react-native-qrcode-styled/assets/13428171/7ed70cb7-437a-4387-a426-1c9c02caa31f)
- Too small

![image](https://github.com/tokkozhin/react-native-qrcode-styled/assets/13428171/ac64c137-40a6-4cbe-a433-bda630497538)
- Too big

**Comment by tokkozhin** [comment]
There is no such possibility yet, but for now you can use [useQRCodeData](https://github.com/tokkozhin/react-native-qrcode-styled/blob/main/src/hooks/useQRCodeData.ts) to get `qrCodeSize` and calculate `pieseSize`

**Comment by Vinod-Mane3021** [comment]
first get the height and width of screen
const deviceWidth = Dimensions.get('screen').width;
const deviceHeight = Dimensions.get('screen').height;

according to that add heigh and width for qr code

this may fix you issue

**Comment by phgn0** [comment]
Okay this is how I implemented a dynamic height / width:

```
export default function QRCode({ link }: { link: string }) {
    const [width, setWidth] = useState<number>(0);
    const padding = 16;
    const data = useQRCodeData(link, {});

    return (
        <View
            onLayout={(event) => {
                const { width } = event.nativeEvent.layout;
                setWidth(width);
            }}
        >
            <QRCodeStyled
                // See https://github.com/tokkozhin/react-native-qrcode-styled
                data={link}
                pieceSize={(width - 2 * padding) / data.qrCodeSize}
                pieceScale={1.02} // fix small gap between pieces
            />
        </View>
    );
}
```

**Comment by ibrahim-ytl** [comment]
Are there any plan to support `size` props in the future? @tokkozhin

**Comment by aymather** [comment]
This is the one annoying thing about this package. Ideally, there would be a `type` parameter which would provide the basic aesthetic of any of the examples provided. Then you could provide a fixed size as a pixel value, or if left empty, would expand to fill the parent container.

It's really tough not to have a way to provide dynamic sizing, or even precise sizing, given the number of different screen sizes, layout dimensions, etc. Dynamic sizing is a must.
