### ISSUE TITLE
Type erros in version 0.3.0

### ISSUE THREAD

**Issue by josefelbez** [tokkozhin/react-native-qrcode-styled#8]
Typescript problems with the version 0.3.0, perhaps we should modify the types as well, if you need help I can assign it to myself and push it as a pr

![image](https://github.com/tokkozhin/react-native-qrcode-styled/assets/12129203/53832a4d-cd5a-4919-b391-024fbdfbab74)
![image](https://github.com/tokkozhin/react-native-qrcode-styled/assets/12129203/c97feada-7726-4d8d-8adb-4bdd80260395)

**Comment by tokkozhin** [comment]
@josefelbez didn't see any problem with this part of code. Could you please provide more details about your environment?

**Comment by josefelbez** [comment]
Yes

```
"typescript": "^5.3.0"
"react-native": "0.73.4",
"react": "18.2.0",

{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"],
      "@env": ["./src/core/env.js"]
    },
    "esModuleInterop": true,
    "checkJs": true,
    "jsx": "react-native",
    "module": "es2022",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "strictNullChecks": true
  },
  "exclude": [
    "node_modules",
    "babel.config.js",
    "metro.config.js",
    "android",
    "ios",
  ]
}
```

**Comment by tokkozhin** [comment]
@josefelbez install @types/qrcode and https://github.com/tokkozhin/react-native-qrcode-styled/releases/tag/v0.3.1

**Comment by josefelbez** [comment]
Hi, sorry for the time it took to answer, i took a break from it.

I can confirm it works now as expected, thank you!
