### ISSUE TITLE
Performance recommendation

### ISSUE THREAD

**Issue by Noitidart** [tokkozhin/react-native-qrcode-styled#9]
Hi, thanks for this great lib. It's very powerful. I am hoping to move from the unmaintained `react-native-qrcode-svg` to this lib. However when I tried it, rendering is much more intensive. Is there any advice to get good performance? 

This was my old code:

```
import QRCode from 'react-native-qrcode-svg';

<QRCode value="uuid_goes_here" size={96} />
```

This is my code when trying this lib:

```
import QRCode from 'react-native-qrcode-styled';

<QRCode data="uuid_goes_here" height={96} width={96} />
```

**Comment by tokkozhin** [comment]
@Noitidart Yes, you are right, this can happen if you had a lot of re-renders. In [0.3.2](https://github.com/tokkozhin/react-native-qrcode-styled/compare/v0.3.1...v0.3.2) I added some memoization, but if you will use `renderCustomPieceItem`, please memoize it and use it with `useCallback`. Thanks for you recommendation!

**Comment by tokkozhin** [comment]
Also, as an alternative way, you can memoize your entire qrcode component

**Comment by Noitidart** [comment]
Thank you! I will test it out. I think it was causing such a lag on first render though, as my modal enterance animation was dropping frames when it contained qr code. I will test and share if memoization helped that.

**Comment by cmd-scholar** [comment]
> Thank you! I will test it out. I think it was causing such a lag on first render though, as my modal enterance animation was dropping frames when it contained qr code. I will test and share if memoization helped that.

Have you been able to fix it?
I i open it in a bottom sheet its rebuilding the whole app before rendering it

**Comment by Noitidart** [comment]
I couldn't figure out how to not hurt performance visually so had to not use this for now. I think it's something I'm doing when using this lib

**Comment by finnholland** [comment]
This is super old but I've gotten it working smoothly by swapping out the SVG for an image once loaded. A little ViewShot trickery to capture the QR and then swap it out to the image. Plus loading the image from cache rather than regenerating each load. 
[Here is a link to the gist](https://gist.github.com/finnholland/a4ce8cbc4a2c838647273cd73774bbc7)

**Comment by Noitidart** [comment]
Oh wow thanks for sharing @finnholland! I have been wanting to use this for awhile but never solved the performance.
